Repository BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo, pull requests merged in 2023-05, with the labels that each got.

#6 SonarLint analysis + added documentation folder
  doc/SonarLint/Initial.png
  doc/SonarLint/SonarLint fixes.md
  doc/SonarLint/Unused.png
  src/Agent.java
  src/AppliedEffect.java
  src/Effect.java
  src/Equipment.java
  src/Field.java
  src/Game.java
  src/General.java
  src/Individual.java
  src/Interface.java
  src/InventoryIncrease.java
  src/JDrawable.java
  src/JEffect.java
  src/JInventory.java
  src/Material.java
  src/Menu.java
  src/Protection.java
  src/Reflect.java
  src/Timer.java
  src/Vaccine.java
  src/View.java
  src/Virologist.java
  src/Virus.java
Labels: bug, documentation, enhancement

#10 Modified build.gradle to include Cucumber dependencies
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  build.gradle
Labels: test

#11 Added IET-HF.md
  IET-HF.md
  README.md
Labels: documentation

#17 fixed player count problems
  src/main/java/iet/hf/monkesoft/electric/boogaloo/View.java
Labels: bug

#19 SonarCloud initial setup
  .github/workflows/build-gradle-project.yml
  build.gradle
Labels: enhancement
